# Generated by Django 4.1.3 on 2022-11-23 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_product_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auth_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 14, 34, 55, 461706, tzinfo=datetime.timezone.utc), verbose_name='Posted on'),
        ),
    ]
