# Generated by Django 4.1.3 on 2022-11-23 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_comment_auth_name_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 14, 53, 6, 426170, tzinfo=datetime.timezone.utc), verbose_name='Posted on'),
        ),
    ]
